# Generated by Django 6.0.7 on 2026-07-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('CA', '🇨🇦 Canada'), ('MA', '🇲🇦 Morocco'), ('PY', '🇵🇾 Paraguay'), ('FR', '🇫🇷 France'), ('BR', '🇧🇷 Brazil'), ('NO', '🇳🇴 Norway'), ('MX', '🇲🇽 Mexico'), ('EN', '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f England'), ('PT', '🇵🇹 Portugal'), ('ES', '🇪🇸 Spain'), ('US', '🇺🇸 United States'), ('BE', '🇧🇪 Belgium'), ('AR', '🇦🇷 Argentina'), ('EG', '🇪🇬 Egypt'), ('CH', '🇨🇭 Switzerland'), ('CO', '🇨🇴 Colombia')], max_length=2)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_11', models.CharField(max_length=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='main_app.team')),
            ],
            options={
                'unique_together': {('team', 'player'), ('team', 'position_in_11')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='main_app.TeamPlayer', to='main_app.player'),
        ),
    ]
